import { writeFile } from "node:fs/promises"

const q = [
    ["https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_a.jpg", "a"],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_akesi.jpg",
        "akesi",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_ala.jpg",
        "ala",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_alasa.jpg",
        "alasa",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_ale.jpg",
        "ale",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_anpa.jpg",
        "anpa",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_ante.jpg",
        "ante",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_anu.jpg",
        "anu",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_awen.jpg",
        "awen",
    ],
    ["https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_e.jpg", "e"],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_en.jpg",
        "en",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_epiku.jpg",
        "epiku",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_esun.jpg",
        "esun",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_ijo.jpg",
        "ijo",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_ike.jpg",
        "ike",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_ilo.jpg",
        "ilo",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_insa.jpg",
        "insa",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_jaki.jpg",
        "jaki",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_jan.jpg",
        "jan",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_jasima.jpg",
        "jasima",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_jelo.jpg",
        "jelo",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_jo.jpg",
        "jo",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_kala.jpg",
        "kala",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_kalama.jpg",
        "kalama",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_kama.jpg",
        "kama",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_kasi.jpg",
        "kasi",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_ken.jpg",
        "ken",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_kepeken.jpg",
        "kepeken",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_kijetesantakalu.jpg",
        "kijetesantakalu",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_kili.jpg",
        "kili",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_kin.jpg",
        "kin",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_kipisi.jpg",
        "kipisi",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_kiwen.jpg",
        "kiwen",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_ko.jpg",
        "ko",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_kokosila.jpg",
        "kokosila",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_kon.jpg",
        "kon",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_kule.jpg",
        "kule",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_kulupu.jpg",
        "kulupu",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_kute.jpg",
        "kute",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_la.jpg",
        "la",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_lanpan.jpg",
        "lanpan",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_lape.jpg",
        "lape",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_laso.jpg",
        "laso",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_lawa.jpg",
        "lawa",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_leko.jpg",
        "leko",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_len.jpg",
        "len",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_lete.jpg",
        "lete",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_li.jpg",
        "li",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_lili.jpg",
        "lili",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_linja.jpg",
        "linja",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_lipu.jpg",
        "lipu",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_loje.jpg",
        "loje",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_lon.jpg",
        "lon",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_luka.jpg",
        "luka",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_lukin.jpg",
        "lukin",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_lupa.jpg",
        "lupa",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_ma.jpg",
        "ma",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_mama.jpg",
        "mama",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_mama_old.jpg",
        "mama_old",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_mani.jpg",
        "mani",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_meli.jpg",
        "meli",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_meso.jpg",
        "meso",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_mi.jpg",
        "mi",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_mije.jpg",
        "mije",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_misekeke.jpg",
        "misikeke",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_moku.jpg",
        "moku",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_moli.jpg",
        "moli",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_monsi.jpg",
        "monsi",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_monsuta.jpg",
        "monsuta",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_mu.jpg",
        "mu",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_mun.jpg",
        "mun",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_musi.jpg",
        "musi",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_mute.jpg",
        "mute",
    ],
    ["https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_n.jpg", "n"],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_namako.jpg",
        "namako",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_nanpa.jpg",
        "nanpa",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_nasa.jpg",
        "nasa",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_nasin.jpg",
        "nasin",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_nena.jpg",
        "nena",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_ni.jpg",
        "ni",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_nimi.jpg",
        "nimi",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_noka.jpg",
        "noka",
    ],
    ["https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_o.jpg", "o"],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_oko.jpg",
        "oko",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_olin.jpg",
        "olin",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_ona.jpg",
        "ona",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_open.jpg",
        "open",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_pakala.jpg",
        "pakala",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_pali.jpg",
        "pali",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_palisa.jpg",
        "palisa",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_pan.jpg",
        "pan",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_pana.jpg",
        "pana",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_pi.jpg",
        "pi",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_pilin.jpg",
        "pilin",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_pimeja.jpg",
        "pimeja",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_pini.jpg",
        "pini",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_pipi.jpg",
        "pipi",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_poka.jpg",
        "poka",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_poki.jpg",
        "poki",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_pona.jpg",
        "pona",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_sama.jpg",
        "sama",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_seli.jpg",
        "seli",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_selo.jpg",
        "selo",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_seme.jpg",
        "seme",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_sewi.jpg",
        "sewi",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_sijelo.jpg",
        "sijelo",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_sike.jpg",
        "sike",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_sin.jpg",
        "sin",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_sina.jpg",
        "sina",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_sinpin.jpg",
        "sinpin",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_sitelen.jpg",
        "sitelen",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_soko.jpg",
        "soko",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_sona.jpg",
        "sona",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_soweli.jpg",
        "soweli",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_suli.jpg",
        "suli",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_suno.jpg",
        "suno",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_supa.jpg",
        "supa",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_suwi.jpg",
        "suwi",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_tan.jpg",
        "tan",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_taso.jpg",
        "taso",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_tawa.jpg",
        "tawa",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_telo.jpg",
        "telo",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_tenpo.jpg",
        "tenpo",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_toki.jpg",
        "toki",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_tomo.jpg",
        "tomo",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_tonsi.jpg",
        "tonsi",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_tu.jpg",
        "tu",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_unpa.jpg",
        "unpa",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_uta.jpg",
        "uta",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_utala.jpg",
        "utala",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_walo.jpg",
        "walo",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_wan.jpg",
        "wan",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_waso.jpg",
        "waso",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_wawa.jpg",
        "wawa",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_weka.jpg",
        "weka",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nimi_wile.jpg",
        "wile",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nmpi_period.jpg",
        "[.]",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nmpi_comma.jpg",
        "[,]",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nmpi_exclamation.jpg",
        "[!]",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nmpi_question.jpg",
        "[?]",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nmpi_colon.jpg",
        "[:]",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nmpi_cartouche.jpg",
        "[cartouche]",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/nimi/t47_nmpi_capsule.jpg",
        "[capsule]",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/kalalili/t47_kalalili_xx.jpg",
        "--",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/kalalili/t47_kalalili_xj.jpg",
        "j-",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/kalalili/t47_kalalili_xk.jpg",
        "k-",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/kalalili/t47_kalalili_xl.jpg",
        "l-",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/kalalili/t47_kalalili_xm.jpg",
        "m-",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/kalalili/t47_kalalili_xn.jpg",
        "n-",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/kalalili/t47_kalalili_xp.jpg",
        "p-",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/kalalili/t47_kalalili_xs.jpg",
        "s-",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/kalalili/t47_kalalili_xt.jpg",
        "t-",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/kalalili/t47_kalalili_xw.jpg",
        "w-",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/kalalili/t47_kalalili_xa.jpg",
        "-a",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/kalalili/t47_kalalili_xe.jpg",
        "-e",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/kalalili/t47_kalalili_xi.jpg",
        "-i",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/kalalili/t47_kalalili_xo.jpg",
        "-o",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/kalalili/t47_kalalili_xu.jpg",
        "-u",
    ],
    [
        "https://jonathangabel.com/images/t47_tokipona/kalalili/t47_kalalili_xxn.jpg",
        "-n",
    ],
].map(async ([img, name]) => {
    const dataView = new DataView(await (await fetch(img!)).arrayBuffer())
    await writeFile(`sitelen-sitelen-${name}.jpg`, dataView)
})

await Promise.all(q)
