export * from "./adjunct"
export * from "./affix"
export * from "./ca"
export * from "./formative"
export * from "./helpers/deep-freeze"
export * from "./helpers/dipthongs"
export * from "./helpers/fill-defaults"
export * from "./helpers/insert-glottal-stop"
export * from "./helpers/permutations"
export * from "./helpers/stress"
export * from "./helpers/vowel-table"
export * from "./helpers/with-wy-alternative"
export * from "./phonotactics"
export * from "./referential"

// TODO: Slot IV/VI shortcuts
